name: "Dependency Review"

on:
  workflow_call:

permissions:
  actions: read
  contents: read
  security-events: write

concurrency:
  group: dependency-review

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v1
